name: Sync 

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: xiaolai
          base: master
          head: master
          pr_title: "Sync from upstream"
